title: '&8Ba lô của %player%'
custom-gui:
  enabled: true
  font: 'haohan:gui'
  prefix: ''
  glyph: ''
  glyphs:
    1: ''
    2: ''
    3: ''
    4: ''
    5: ''
    6: ''
rows: 6
backpack-item-name: 'Backpack'
backpack-item-model: 'haohan:backpack'
backpack-item-lore:
  - '&7Chuột phải để mở ba lô cá nhân.'
  - '&8Dung lượng: 53 ô + 1 module'
database:
  file: backpacks.db
backpack-limit:
  enabled: false
  default: 1
blocked-materials: []
keep-backpacks-after-death: true
block-backpack-in-containers: true
allow-backpacks-inside-backpacks: false
hopper:
  enabled: true
backpack-collision:
  enabled: true
worn-backpack:
  enabled: true
  offset:
    back: 0.26 # Khoảng cách lùi ra sau lưng (block)
    height: 0.75 # Độ cao vị trí đeo sau lưng khi đứng (block)
    sneak-height: 0.70 # Độ cao vị trí đeo sau lưng khi ngồi Shift (block)


